version: '3.8'
services:
  postgrestp:
    image: postgres:13.2
    container_name: postgrestp
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: tpeng
      POSTGRES_DB: tpeng
    ports:
      - 5432:5432
    volumes:
      - /home/docker/volumes/db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - postgrestpnt
  ll:
    container_name: ll
    build: 
      context: ./
    working_dir: /app
    ports:
      - "30000:30000"
      - "3000:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - postgrestpnt
networks:
  postgrestpnt:
    driver: bridge